name: Update README daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write   # cấp quyền ghi vào repo

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          if grep -q "Last updated at" README.md; then
            sed -i "s/^Last updated at.*/Last updated at $(date)/" README.md
          else
            echo "\nLast updated at $(date)" >> README.md
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto update readme $(date)" || echo "No changes to commit"
          git push
